### ISSUE TITLE
Fabric Network

### ISSUE THREAD

**Issue by HSGamer** [etases/EduBlock.MiniNet#1]
# Description
Create scripts to initialize the network and install the ChainCode from [EduBlock.CC](https://github.com/etases/EduBlock.CC)

# Tasks
* [x] Create network scripts
* [x] Create chaincode installation scripts
* [x] Test the system

# Note
